export const AUTH_SESSION_INVALIDATION_CODES = Object.freeze([
  "AUTH_TOKEN_MISSING",
  "AUTH_TOKEN_INVALID",
  "AUTH_TOKEN_EXPIRED",
  "AUTH_TOKEN_REVOKED",
  "AUTH_IDLE_TIMEOUT",
  "AUTH_USER_INACTIVE",
]);

export const CONTEXT_INVALIDATION_CODES = Object.freeze([
  "CONTEXT_REQUIRED",
  "INVALID_ACTIVE_CONTEXT",
]);
